docs: update babelrc for storybook
doccoio/docco pull request #7
Opened 2022-11-16 09:32 UTC by LucasHartridge

Storybook reads babel by default from `.babelrc.json` https://storybook.js.org/docs/react/configure/babel#generate-a-babelrc

2022-11-16 10:58 UTC, jcunhafonte approved these changes, later dismissed

2022-11-23 10:59 UTC, jcunhafonte requested changes

2022-11-24 07:57 UTC, LucasHartridge commented on CONTRIBUTING.md
> -+{{"demo": "pages/components/buttons/SuperButtons.js"}}
What I removed? Or the section I added ?

2022-11-24 07:59 UTC, LucasHartridge commented on README.md
> +[Mui-url]: https://github.com/mui/material-ui
This is a good practice to keep all the Img Shields and URLs in a central place. Do you like this way or do you still prefer the old one? 

I know is more verbose but is a good practice

2022-11-24 08:02 UTC, LucasHartridge commented on README.md
> +| Demo                                     | Usage  | Description                                                       |
I looked on Docco WIp and I did not found such examples, Which paragraph are you referring?

2022-11-24 22:49 UTC, jcunhafonte approved these changes

2022-11-24 22:49 UTC, merged